# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_pixiv_fields_for_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedimage',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
