# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_add_image_model_show_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedimage',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
