# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_sourcedimage_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedimage',
            name='da_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sourcedimage',
            name='da_path',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sourcedimage',
            name='da_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sourcedimage',
            unique_together=set([('da_username', 'da_path'), ('pixiv_id', 'pixiv_order')]),
        ),
    ]
